server {
     listen 80;
     server_name mmd-massotherapie.fr www.mmd-massotherapie.fr;

     root /usr/share/nginx/html/browser;
     index index.html;

     location / {
         try_files $uri $uri/ /index.html;
     }
      # Cache statics folders
      location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|webp)$ {
           expires 30d;
           add_header Cache-Control "public";
      }
}
