app.security.jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
app.security.jwt.expiration-ms=3600000
app.security.cors.allowed-origins=http://localhost:4200
app.security.admin.registration-invitation-code=test-admin-invitation-code

spring.datasource.url=jdbc:h2:mem:mmd_test;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

spring.flyway.enabled=false