# Profile PROD

# ===============================
# Datasource configuration
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# ===============================
# Jwt
# ===============================
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-ms=${JWT_EXPIRATION}
app.security.cors.allowed-origins=https://www.mmd-massotherapie.fr,https://mmd-massotherapie.fr

# ===============================
# Logs
# ===============================
logging.level.root=INFO

# ===============================
# Server
# ===============================
server.error.include-message=never
server.error.include-stacktrace=never